- name: add nginx PPA
  become: yes
  apt_repository: repo=ppa:nginx/stable

- name: install 'nginx'
  become: yes
  apt: pkg=nginx-extras state=present

- name: delete nginx default config
  become: yes
  file: >
    path=/etc/nginx/sites-available/default
    state=absent
  notify: restart nginx

- name: delete nginx default config symlink
  become: yes
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify: restart nginx

- name: create directory for cache
  become: yes
  file: >
    path={{ nginx_extras.cache_dir }}
    state=directory
    owner={{ nginx_extras.cache_user }}
    group={{ nginx_extras.cache_group }}
  when: nginx_extras.cache_dir is defined

- name: fix logrotate.d config
  become: yes
  replace: >
    dest=/etc/logrotate.d/nginx
    regexp='^(\s+)invoke-rc\.d\s+nginx\s+rotate.*$'
    replace='\1[ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`'
    validate='/usr/sbin/logrotate -df %s'
